# Generated by Django 6.0.4 on 2026-04-23 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="tournaments_image/"
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("place", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referee", models.CharField(max_length=100)),
                (
                    "result",
                    models.CharField(
                        choices=[("Red", "Красные"), ("Black", "Чёрные")],
                        default="Red",
                        max_length=20,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="games.tournament",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foul",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        default=0,
                    ),
                ),
                (
                    "tech_foul",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (2, "2")], default=0
                    ),
                ),
                (
                    "play_role",
                    models.CharField(
                        choices=[
                            ("mafia", "Мафия"),
                            ("don", "Дон"),
                            ("sheriff", "Шериф"),
                            ("civilian", "Мирный"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "score_plus",
                    models.DecimalField(decimal_places=1, max_digits=5, null=True),
                ),
                (
                    "score_minus",
                    models.DecimalField(decimal_places=1, max_digits=5, null=True),
                ),
                (
                    "score_ci",
                    models.DecimalField(decimal_places=1, max_digits=5, null=True),
                ),
                ("thoughts", models.TextField(blank=True, null=True)),
                ("protocol", models.TextField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
            ],
        ),
    ]
