# Generated by Django 6.0.4 on 2026-05-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/tournament_images/"
            ),
        ),
    ]
