# Generated by Django 6.0.4 on 2026-05-10 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_alter_tournament_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userplay",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="games.game",
            ),
        ),
    ]
